In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
a = np.array([[1,3],[0,-2]])
print("This is numpy array\n ",a)
eigvals,eigvecs=np.linalg.eig(a)
print("Eigen Values: ",eigvals)
print("Eigen Vectors: \n",eigvecs)

This is numpy array
  [[ 1  3]
 [ 0 -2]]
Eigen Values:  [ 1. -2.]
Eigen Vectors: 
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [11]:
a = np.array([1.4, 2.1, 3.6, 4.6]) 
bins = np.array([1.0, 1.2, 2.5, 4.2, 9.0]) 
   
# using np.digitize() method 
h = np.digitize(a, bins) 
   
print(h) 

[2 2 3 4]


In [13]:
#Working on 1D 
arr = np.arange(5) 
print("arr : \n", arr) 

repetitions = 2
a = np.repeat(arr, repetitions) 
print("\nRepeating arr 2 times : \n", a) 
print("Shape : ", a.shape) 

repetitions = 3
a = np.repeat(arr, repetitions) 
print("\nRepeating arr 3 times : \n", a) 
print("Shape : ", a.shape) 


arr : 
 [0 1 2 3 4]

Repeating arr 2 times : 
 [0 0 1 1 2 2 3 3 4 4]
Shape :  (10,)

Repeating arr 3 times : 
 [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4]
Shape :  (15,)


In [14]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]]) 

print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape) 

out_arr =np.squeeze(in_arr) 

print ("output squeezed array : ", out_arr) 
print("Shape of output array : ", out_arr.shape) 


Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


In [15]:
c=np.linspace(2.0, 3.0, num=5)
c

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [16]:
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ] 
print ("Input array : ", in_array) 

out_array = np.clip(in_array, a_min = 2, a_max = 6) 
print ("Output array : ", out_array) 

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


In [18]:
arr = np.arange(6).reshape((2, 3))
print(arr)
con = np.mod(arr, 3)==0
print(con)
np.extract(con, arr)

[[0 1 2]
 [3 4 5]]
[[ True False False]
 [ True False False]]


array([0, 3])

In [23]:
x = np.array([8, 4, 2, 5])
x[np.argpartition(x, 2)]

array([2, 4, 5, 8])

In [24]:
arr1 = [5, 6, 2, 3, 4] 
arr2 = [1, 2, 3] 

g = np.setdiff1d(arr1, arr2) 

print (g) 


[4 5 6]


In [26]:
arr = np.array([1, 2, 3, 4], dtype = np.float64) 

gg = arr.itemsize 

print (gg) 


8


In [27]:
in_arr1 = np.array([ 5, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([ 7, 8, 3] ) 
print ("2nd Input array : \n", in_arr2) 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 


1st Input array : 
 [5 2 3]
2nd Input array : 
 [7 8 3]
Output horizontally stacked array:
  [5 2 3 7 8 3]


In [29]:
# Stacking the two arrays vertically 
out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr) 

Output vertically stacked array:
  [[5 2 3]
 [7 8 3]]


In [30]:
arr = np.arange(27.0).reshape(3, 3, 3) 

r = np.hsplit(arr, 1) 

print (r) 


[array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])]


In [32]:
arr = np.arange(16.0).reshape(4,4) 

r = np.vsplit(arr, 1) 

print (r)

[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [36]:
a = np.arange(6).reshape(3,2) 
print ('Array a:' )
print (a)  
print ('Create view of a:' )
b = a.view() 
print (b)  
print ('id() for both the arrays are different:' )
print ('id() of a:')
print (id(a))
print ('id() of b:' )
print (id(b))  
b.shape = 2,3 
print ('Shape of b:' )
print (b)
print ('Shape of a:' )
print (a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
1682765954544
id() of b:
1682765954224
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [38]:
# importing "copy" for copy operations 
import copy 
li1 = [1, 2, [3,5], 4] 
li2 = copy.deepcopy(li1) 

# original elements of list 
print ("The original elements before deep copying") 
for i in range(0,len(li1)): 
    print (li1[i],end=" ") 

print("\r") 

# adding and element to new list 
li2[2][0] = 8

# Change is reflected in l2 
print ("The new list of elements after deep copying ") 
for i in range(0,len( li1)): 
    print (li2[i],end=" ") 

print("\r") 

# Change is NOT reflected in original list as it is a deep copy 
print ("The original elements after deep copying") 
for i in range(0,len( li1)): 
    print (li1[i],end=" ") 


The original elements before deep copying
1 2 [3, 5] 4 
The new list of elements after deep copying 
1 2 [8, 5] 4 
The original elements after deep copying
1 2 [3, 5] 4 

In [39]:
lis1 = [ 1, 9, 7, 4 ] 
lis2 = lis1.copy() 

print ("The new list created is : " + str(lis2)) 
lis2.append(5) 

# Printing lists after adding new element 
# No change in old list 
print ("The new list after adding new element : " + str(lis2)) 
print ("The old list after adding new element to new list : " + str(lis1)) 


The new list created is : [1, 9, 7, 4]
The new list after adding new element : [1, 9, 7, 4, 5]
The old list after adding new element to new list : [1, 9, 7, 4]


In [40]:
x = np.linspace(-2, 3, 9)
y = np.linspace(-5, 6, 11)
# meshgrid two 2-dimensional arrays 
x_1, y_1 = np.meshgrid(x, y)
print("x_1 Matrix: ")
print(x_1)
print("y_1 Matrix: ")
print(y_1)

x_1 Matrix: 
[[-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]
 [-2.    -1.375 -0.75  -0.125  0.5    1.125  1.75   2.375  3.   ]]
y_1 Matrix: 
[[-5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5. ]
 [-3.9 -3.9 -3.9 -3.9 -3.9 -3.9 -3.9 -3.9 -3.9]
 [-2.8 -2.8 -2.8 -2.8 -2.8 -2.8 -2.8 -2.8 -2.8]
 [-1.7 -1.7 -1.7 -1.7 -1.7 -1.7 -1.7 -1.7 -1.7]
 [-0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6]
 [ 0.5 

In [41]:
arr = np.array([[2, 4, 6]]) 

f = np.swapaxes(arr, 0, 1) 

print (f) 


[[2]
 [4]
 [6]]


In [43]:
in_arr1 = np.array(( 1, 8, 3 )) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array(( 4, 5, 7 )) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays 
out_arr = np.column_stack((in_arr1, in_arr2)) 
print ("Output stacked array:\n ", out_arr) 


1st Input array : 
 [1 8 3]
2nd Input array : 
 [4 5 7]
Output stacked array:
  [[1 4]
 [8 5]
 [3 7]]
