In [2]:
import numpy as np

#  Question 1

In [4]:
t=np.array(range(2,51,3))
print(t)
print(type(t))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


# Question 2

In [5]:
#list
t2=[]
t3=[]
#Getting input from user
for i in range(0,5):
    elt=int(input())
    t2.append(elt)
print(t2)
print()
for i in range(0,5):
    elt=int(input())
    t3.append(elt)
print(t3)
print()

#converting list to numpy arrays
a=np.array(t2)
b=np.array(t3)

#Array after concatenation
d=np.concatenate((a,b))
c=np.array(d)
print((c))
print()

#sorted numpy array
print(np.sort(c))


1
3
56
2
6
[1, 3, 56, 2, 6]

7
5
44
23
0
[7, 5, 44, 23, 0]

[ 1  3 56  2  6  7  5 44 23  0]

[ 0  1  2  3  5  6  7 23 44 56]


# Question 3

In [11]:
e=np.asarray([[1,2,3,4],[2,3,6,7]],dtype=int)
#dimension of the ndarray
print(e.ndim)
#size of the ndarray
print(e.size)

2
8


# Question 4

In [31]:
#conversion of 1D array to 2D array using reshape function
e=np.asarray([[1,2,3,4],[2,3,6,7]],dtype=int)
f=np.reshape(e,(4,2))
print(f)
print("\nshape of array after using reshape():",np.shape(f))
print()
#conversion using newaxis()
f=e[:,np.newaxis] 
print(f)
print()
print("shape of array after using newaxis():",np.shape(f))


[[1 2]
 [3 4]
 [2 3]
 [6 7]]

shape of array after using reshape(): (4, 2)

[[[1 2 3 4]]

 [[2 3 6 7]]]

shape of array after using newaxis(): (2, 1, 4)


# Question 5

In [39]:
e=np.array([[4,1],[6,5],[6,7],[9,5]])
f=np.array([[2,1],[3,5],[6,4],[9,7]])
#Vertical stacking
print("Vertical stacking\n",np.vstack((e,f)))

print()
print("Horizontal stacking\n",np.hstack((e,f)))

Vertical stacking
 [[4 1]
 [6 5]
 [6 7]
 [9 5]
 [2 1]
 [3 5]
 [6 4]
 [9 7]]

Horizontal stacking
 [[4 1 2 1]
 [6 5 3 5]
 [6 7 6 4]
 [9 5 9 7]]


# Question 6

In [29]:
print("-------------------------------------\nTo find unique elements in ndarray\n-------------------------------------")
arr = np.array([[11, 11, 12, 13],[14, 15, 16, 17],[12, 13, 11, 14]])
uniqueValues = np.unique(arr)
print('Unique Values : ', uniqueValues)
print()
uniqueValues, occurCount = np.unique(arr, return_counts=True)
listOfUniqueValues = zip(uniqueValues, occurCount)
print('------------------------------------------\nUnique Values along with occurrence Count')
print("------------------------------------------")
print("Unique values :",uniqueValues)
print()
print("Occurence count :",occurCount)

-------------------------------------
To find unique elements in ndarray
-------------------------------------
Unique Values :  [11 12 13 14 15 16 17]

------------------------------------------
Unique Values along with occurrence Count
------------------------------------------
Unique values : [11 12 13 14 15 16 17]

Occurence count : [3 2 2 2 1 1 1]
